# Generated by Django 4.2.2 on 2023-06-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=35, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('mensaje', models.TextField(max_length=500, verbose_name='Mensaje')),
            ],
        ),
    ]
